name: Build and Release with pyinstaller
on:
  push:
    branches:
      - main
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: pip install pyinstaller
    - name: Build executable
      run: pyinstaller main.py --onefile
    - name: Get upload URL
      id: upload
      uses: actions/upload-artifact@v2
      with:
        name: ReleaseArtifact
    - name: Upload to release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.upload.outputs.upload_url }}
        asset_path: ./dist/main
        asset_name: ascii-art-generator
        asset_content_type: application/octet-stream
        token: ${{ secrets.PAT }}
