name: Build and Release with PyInstaller
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: pip install pyinstaller
    - name: Build executable
      run: pyinstaller main.py --onefile
    - name: Upload to release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./dist/your_script
        asset_name: ascii-art-generator
        asset_content_type: application/octet-stream
        token: ${{ secrets.GITHUB_TOKEN }}
