name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - name: Get latest release number
      run: echo "::set-env name=RELEASE_NUMBER::$(curl --silent https://api.github.com/repos/$GITHUB_REPOSITORY/releases/latest | grep '\"tag_name\":' |  sed -E 's/.*"([^"]+)".*/\1/' | tr -d 'v')"
      id: get_release_number
      shell: bash
    - name: Increment release number
      run: echo $(( ${RELEASE_NUMBER} + 1 )) >> $GITHUB_ENV
      id: increment_release_number
      shell: bash
    - name: Install PyInstaller
      run: pip install pyinstaller
    - name: Build Binary
      run: pyinstaller main.py --onefile
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      with:
        tag_name: v${{ env.RELEASE_NUMBER }}.${{ env.INCREMENT_RELEASE_NUMBER }}.0
        release_name: Release ${{ env.INCREMENT_RELEASE_NUMBER }}.0.0
        body: 'New release'
        draft: false
        prerelease: false
    - name: Upload Binary
      id: upload-release-assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/main
        asset_name: ascii-art-generator
        asset_content_type: application/octet-stream
